=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenfgaClient::StoresApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StoresApi' do
  before do
    # run before each test
    @api_instance = OpenfgaClient::StoresApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StoresApi' do
    it 'should create an instance of StoresApi' do
      expect(@api_instance).to be_instance_of(OpenfgaClient::StoresApi)
    end
  end

  # unit tests for create_store
  # Create a store
  # Create a unique OpenFGA store which will be used to store authorization models and relationship tuples.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [CreateStoreResponse]
  describe 'create_store test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_store
  # Delete a store
  # Delete an OpenFGA store. This does not delete the data associated with the store, like tuples or authorization models.
  # @param store_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_store test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_store
  # Get a store
  # Returns an OpenFGA store by its identifier
  # @param store_id 
  # @param [Hash] opts the optional parameters
  # @return [GetStoreResponse]
  describe 'get_store test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_stores
  # List all stores
  # Returns a paginated list of OpenFGA stores and a continuation token to get additional stores. The continuation token will be empty if there are no more stores. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size 
  # @option opts [String] :continuation_token 
  # @return [ListStoresResponse]
  describe 'list_stores test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
