=begin
#OpenFGA

#A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.

The version of the OpenAPI document: 1.x
Contact: community@openfga.dev
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenfgaClient::V1TupleToUserset
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenfgaClient::V1TupleToUserset do
  let(:instance) { OpenfgaClient::V1TupleToUserset.new }

  describe 'test an instance of V1TupleToUserset' do
    it 'should create an instance of V1TupleToUserset' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenfgaClient::V1TupleToUserset)
    end
  end

  describe 'test attribute "tupleset"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "computed_userset"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
